#+title: KVOS
#+HTML_HEAD: <link rel="stylesheet" href="./style.css">
#+OPTIONS: toc:nil num:nil timestamp:nil html-style:nil title:nil

#+begin_export html
<nav id="nav">
    <ul>
       <li class="current">
           <a href="./index.html">Home</a>
       <li class="">
           <a href="./screenshots.html">Screenshots</a>
       <li class="">
           <a href="./installation.html">Install KVOS</a>
       <li class="">
           <a href="./guide.html">Guide</a>
       <li class="">
           <a href="./software.html">Pre-Installed</a>
    </ul>
</nav>
#+end_export

* KVOS
:PROPERTIES:
:HTML_CONTAINER_CLASS: boxed
:END:
This is my custom i3wm based desktop. This is tested on an vanilla arch install. This is a lightweight and fast desktop. It is light on system resources and [[./software.org][didn't install many packages]].

-----
* Get Started
:PROPERTIES:
:HTML_CONTAINER_CLASS: boxed
:END:
** Lightweigth
Lightweigth linux distro. Small memory and storage overhead. Even the processors are at ease.
** Arch BTW!
Just some i3 config filed on top of vanilla arch. And one extra repository to get you some beautiful wallpapers.
** Productive
Tiling window managers are objectively better than floating window managers. And manual better than dynamic.
** Customizable
Customising KVOS is extremely easy. All custumization is done inside config files. That too inside emacs org mode.
