#+title: Install Instructions
#+HTML_HEAD: <link rel="stylesheet" href="./style.css">
#+HTML_HEAD: <script src="./menu.js"></script>
#+OPTIONS: toc:nil num:nil timestamp:nil html-style:nil title:nil

#+begin_export html
<div class="nav" id="nav">
    <a href="javascript:void(0);" onclick="myFunction()" class="menuicon"><b>MENU</b></a>
    <a href="./index.html">Home</a>
    <a href="./screenshots.html">Screenshots</a>
    <a href="./installation.html" class="current">Install KVOS</a>
    <a href="./guide.html">Guide</a>
    <a href="./software.html">Pre-Installed</a>
</div>
#+end_export

* Installing KVOS
One can setup KVOS on a fresh setup of vanilla arch install by running the [[file:static/scripts/kvos-setup.sh][kvos-setup.sh]] script.

There is also a script provided for installing vanilla arch. Let's start with that.
** Install base arch linux
- Download an Arch Linux ISO and write it to a USB
- Boot from the live USB and connect to the internet
- From the command line execute following command
  #+begin_src bash
bash <(curl -s https://kanishakvaidya.github.io/arch-install.sh)
  #+end_src
- This will execute my [[file:static/scripts/arch-install.sh][arch install]] script
- This script will guide you through base arch install. (partitions and ~pacstrap~)
- Read the details about the scripts from the repository.
- [[file:static/scripts/configuration-script.sh][configuration-script.sh]] will be executed automatically by this script. Here you need to configure
  + Hostname
  + root user password
  + New user with its password
** KVOS installation
- Download the [[file:static/scripts/kvos-setup.sh][kvos-setup.sh]] script and run it from your user account. You can use the following command to download and run the script:
  #+begin_src bash
bash <(curl -s https://kanishakvaidya.github.io/kvos-setup.sh)
  #+end_src
- This script will add [[https://github.com/KanishakVaidya/kv-arch-repo][kv-arch-repo]] to the repository list. It will open [[file:static/scripts/packages.md][packages.md]] file in a text editor. Check the boxes corresponding to the softwares you want to install. You can also add your own software to the list by appending them to a section with -[X]
- The directories in your ~$HOME~ will have shortened names for better accessibility from terminal.
- Default theme is Materia Dark and default icon theme is Papirus.
- Customize qt based apps using ~qt5ct~ and ~kvantum~, customize gtk apps using ~lxappearance~.
