#+title: Pre Installed packages
#+HTML_HEAD: <link rel="stylesheet" href="./style.css">
#+OPTIONS: toc:nil num:nil timestamp:nil html-style:nil title:nil

#+begin_export html
<nav id="nav">
    <ul>
       <li class="">
           <a href="./index.html">Home</a>
       <li class="">
           <a href="./screenshots.html">Screenshots</a>
       <li class="">
           <a href="./installation.html">Install KVOS</a>
       <li class="">
           <a href="./guide.html">Guide</a>
       <li class="current">
           <a href="./software.html">Pre-Installed</a>
    </ul>
</nav>

#+end_export

The following packages will be installed with *KVOS installation script*.
These packages are mentioned in [[file:static/scripts/packages.md][packages.md]] file. Heading of every category has a ~- [ ]~ in front of it. Change it to ~- [X]~ to install packages written below the ~- [X]~ line. Other packages will be ignored.
*** Base (Mandatory)
alacritty arandr autoconf automake base bison blueman conky dunst efibootmgr exa fakeroot feh firefox flameshot flex fzf gcc geany git gvfs gvfs-mtp htop i3-gaps i3blocks i3lock jack2 kvantum libtool lxappearance-gtk3 lxqt-archiver lxsession-gtk3 m4 make man-db materia-gtk-theme neovim networkmanager network-manager-applet nodejs ntfs-3g otf-font-awesome patch pavucontrol-qt pcmanfm-qt picom pkgconf pulseaudio pulseaudio-alsa pulseaudio-bluetooth qt5ct ranger ripgrep rofi rsync sed smplayer smplayer-skins smplayer-themes sshfs starship ttf-dejavu ttf-hack ttf-indic-otf ttf-nerd-fonts-symbols-2048-em-mono udiskie unzip vte3 which xcolor xdg-user-dirs yarn zathura zathura-pdf-mupdf zip zsh zsh-autosuggestions zsh-completions zsh-syntax-highlighting

*** Utilities
imagemagick rclone vlc v4l2loopback-dkms v4l2loopback-utils w3m xournalpp youtube-dl xf86-input-wacom

*** Xorg (Mandatory)
xorg-server xorg-xinit

*** amd-drivers
amd-ucode mesa xf86-video-amdgpu

*** intel-drivers
intel-ucode mesa xf86-video-intel

*** nvidia drivers
nvidia nvidia-prime nvidia-utils nvtop

*** Office suit
libreoffice-fresh

*** Development
emacs pyright python-pip

*** TeX/LaTeX
texlive-most
